### ISSUE TITLE
[Incompatibility] Dupe Bug with Advanced Chests Plugin

### ISSUE THREAD

**Issue by sphings79** [SoulLength/PortableChests#5]
If you have Advanced Chests installed and this plugin and break the advanced chest 2 chest will bedropped.
The Advanced Chest and the chest from your Plugin.

**Comment by SoulLength** [comment]
Hello, can't test that plugin properly since it's not free or opensource but seems like it's dodging the event.setDropItems(false) in my plugin. Anyway i released a [new update](https://github.com/SoulLength/PortableChests/releases/tag/1.5.0), where i changed the BlockBreakEvent priority, check it out and let me know if anything changed.

**Comment by sphings79** [comment]
We are no longer using advanced chest. so i think we can close that.
